runtime: nodejs8
env_variables:
  GCLOUD_STORAGE_BUCKET: shopping-checkout-221908.appspot.com
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50